// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGA1uXVr_DyDi88l-SifKHuEg_WGHOFac',
    appId: '1:706615812882:web:94729c3095654515c449cb',
    messagingSenderId: '706615812882',
    projectId: 'mad-projects-y2',
    authDomain: 'mad-projects-y2.firebaseapp.com',
    storageBucket: 'mad-projects-y2.firebasestorage.app',
    measurementId: 'G-XJ1P6BQSCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJDOSDA6al1xu1GrIViwzG_ICt2PbLpHM',
    appId: '1:706615812882:android:987ad1839a2875f9c449cb',
    messagingSenderId: '706615812882',
    projectId: 'mad-projects-y2',
    storageBucket: 'mad-projects-y2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmRPqTPiYGC2GgkvzKg3hbGwJ2Bc4yFlE',
    appId: '1:706615812882:ios:d8c816c9229d6742c449cb',
    messagingSenderId: '706615812882',
    projectId: 'mad-projects-y2',
    storageBucket: 'mad-projects-y2.firebasestorage.app',
    iosClientId: '706615812882-h122i8drid0rkkh3iar35d6kvqutaoan.apps.googleusercontent.com',
    iosBundleId: 'com.example.madGroupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmRPqTPiYGC2GgkvzKg3hbGwJ2Bc4yFlE',
    appId: '1:706615812882:ios:d8c816c9229d6742c449cb',
    messagingSenderId: '706615812882',
    projectId: 'mad-projects-y2',
    storageBucket: 'mad-projects-y2.firebasestorage.app',
    iosClientId: '706615812882-h122i8drid0rkkh3iar35d6kvqutaoan.apps.googleusercontent.com',
    iosBundleId: 'com.example.madGroupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGA1uXVr_DyDi88l-SifKHuEg_WGHOFac',
    appId: '1:706615812882:web:672919b1acd5fb7cc449cb',
    messagingSenderId: '706615812882',
    projectId: 'mad-projects-y2',
    authDomain: 'mad-projects-y2.firebaseapp.com',
    storageBucket: 'mad-projects-y2.firebasestorage.app',
    measurementId: 'G-GMZL4E36P3',
  );

}